"use client";

import React, { createContext, useContext, useState, ReactNode } from 'react';
import * as enData from '@/data/mockData';
import * as deData from '@/data/mockDataDe';
import * as roData from '@/data/mockDataRo';
import * as frData from '@/data/mockDataFr';

export type Language = 'en' | 'de' | 'ro' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  data: typeof enData;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const dataMap = {
  en: enData,
  de: deData,
  ro: roData,
  fr: frData
};

export const translations: Record<Language, Record<string, string>> = {
  en: {
    "getInTouch": "Get In Touch",
    "contactIntro": "Whether you have a question, a project proposal, or just want to say hi, I'll try my best to get back to you!",
    "name": "Name",
    "email": "Email",
    "subject": "Subject",
    "message": "Message",
    "sendMessage": "Send Message",
    "sending": "Sending...",
    "projects": "Projects",
    "experience": "Work Experience",
    "education": "Education",
    "about": "About Me",
    "contact": "Contact Me",
    "explorer": "Explorer",
    "search": "Search",
    "searchPlaceholder": "Search (Ctrl+Shift+F)",
    "clearSearch": "Clear Search",
    "noResults": "No results found for",
    "githubStats": "GitHub Stats",
    "linkedinProfile": "LinkedIn Profile",
    "resume": "Resume",
    "viewResume": "View Resume",
    "downloadResume": "Download Resume",
    "allRightsReserved": "All rights reserved",
    "builtWith": "Built with",
    "and": "and",
    "biography": "Biography",
    "contactMe": "Contact Me",
    "switchLanguage": "Switch Language",
    "switchTheme": "Switch Theme",
    "settings": "Settings",
    "phoneOptional": "Phone (Optional)",
    "purpose": "Purpose",
    "locationPreference": "Location Preference",
    "remote": "Remote",
    "hybrid": "Hybrid",
    "onsite": "On-site",
    "addressLabel": "Address for distance calculation",
    "officeAddressPlaceholder": "Office Address (Street, City, Country)",
    "checkingDistance": "Checking distance...",
    "fromKirchheim": "from Kirchheim",
    "technologies": "Technologies",
    "techPlaceholder": "Type tech and press Enter (e.g. Java, React)",
    "buyTemplate": "Buy This Website Template",
    "buyTemplateMessage": "This template is designed to easily import your LinkedIn data. I'll send you the setup instructions!",
    "recruitingCompany": "Recruiting (My Company)",
    "recruitingClient": "Recruiting (For a Client)",
    "personalProject": "Personal Project / Freelance",
    "techError": "I do not accept projects involving {tech}. I specialize in Java/Spring & JS/React ecosystems.",
    "distanceError": "Distance is {distance}km. I only accept on-site offers within 25km of my location, Relocation is not an option, inside Germany.",
    "addressNotFound": "Could not find this address. Please try to be more specific.",
    "addressError": "Error checking location. Please try again.",
    "addressRequired": "Address is required for on-site/hybrid offers.",
    "successMessage": "Thank you!",
    "emailSent": "Email Sent",
    "notContacted": "Not Contacted Yet",
    "results": "results",
    institutionLabel: "institution=",
    degreeLabel: "degree=",
    yearLabel: "year=",
    locationLabel: "location=",
    companyLabel: "company=",
    timeLabel: "time=",
    typeLabel: "type=",
    sizeLabel: "size=",
    educationLabel: "education=",
    showDetails: "Show Details",
    showLess: "Show Less",
    cooldownMessage: "You can send another message in",
    sendAnother: "Send another message",
    errorMessage: "Failed to send message. Please try again later or contact me directly via email.",
    mainBranch: "main*",
    portfolioLabel: "PORTFOLIO",
    viewProfile: "View Profile",
    connections: "connections",
    readMore: "Read More",
    topSkills: "Top Skills",
    certificationsLabel: "Certifications",
    joined: "Joined",
    repositories: "Repositories",
    contributions: "Contributions (Last Year)",
    achievements: "Achievements",
    loadingGithub: "Loading GitHub Profile...",
    errorGithub: "Could not load GitHub profile",
    portfolioTitle: "portfolio - Antigravity - liviuionesi.dev",
    lnCol: "Ln 1, Col 1",
    utf8: "UTF-8",
    zoom: "100%",
    viewCode: "View Code",
    liveDemo: "Live Demo",
    stackLabel: "stack=",
    loading: "Loading...",
    error: "Error",
    aboutFile: "About.tsx",
    experienceFile: "Experience.java",
    educationFile: "Education.tsx",
    projectsFile: "Projects.json",
    contactFile: "Contact.tsx",
    quickDraw: "Quick Draw",
    pullShark: "Pull Shark",
    yolo: "YOLO",
    srcFolder: "src",
    cvGenerator: "CV Generator",
    cvConfig: "CV Configuration",
    contentDetail: "Content Detail",
    briefSummary: "Brief Summary",
    detailedView: "Detailed View",
    sections: "Sections",
    includeProjects: "Include Projects",
    visualStyle: "Visual Style",
    printOptimized: "Print Optimized",
    ideTheme: "IDE Theme",
    openPrintableCV: "Open Printable Version",
    briefSummaryDesc: "Compact view with summaries only. Best for quick scanning.",
    detailedViewDesc: "Includes full professional biography and complete job descriptions.",
    printOptimizedDesc: "Clean white background, optimized for physical paper printing.",
    ideThemeDesc: "Uses the portfolio's dark theme. Best for PDF sharing.",
    openInNewTabDesc: "Opens in a new tab. Use your browser's print dialog (Ctrl+P) to save as PDF.",
  },
  de: {
    "getInTouch": "Kontakt aufnehmen",
    "contactIntro": "Ob Sie eine Frage haben, einen Projektvorschlag oder einfach nur Hallo sagen wollen, ich werde mein Bestes geben, um Ihnen zu antworten!",
    "name": "Name",
    "email": "E-Mail",
    "subject": "Betreff",
    "message": "Nachricht",
    "sendMessage": "Nachricht senden",
    "sending": "Senden...",
    "projects": "Projekte",
    "experience": "Berufserfahrung",
    "education": "Ausbildung",
    "about": "Über mich",
    "contact": "Kontakt",
    "explorer": "Explorer",
    "search": "Suche",
    "searchPlaceholder": "Suchen (Ctrl+Shift+F)",
    "clearSearch": "Suche löschen",
    "noResults": "Keine Ergebnisse gefunden für",
    "githubStats": "GitHub-Profil",
    "linkedinProfile": "LinkedIn-Profil",
    "resume": "Lebenslauf",
    "viewResume": "Lebenslauf ansehen",
    "downloadResume": "Lebenslauf herunterladen",
    "allRightsReserved": "Alle Rechte vorbehalten",
    "builtWith": "Erstellt mit",
    "and": "und",
    "biography": "Biografie",
    "contactMe": "Kontaktieren Sie mich",
    "switchLanguage": "Sprache wechseln",
    "switchTheme": "Design wechseln",
    "settings": "Einstellungen",
    "phoneOptional": "Telefon (Optional)",
    "purpose": "Zweck",
    "locationPreference": "Standortpräferenz",
    "remote": "Remote",
    "hybrid": "Hybrid",
    "onsite": "Vor Ort",
    "addressLabel": "Adresse für Entfernungsberechnung",
    "officeAddressPlaceholder": "Büroadresse (Straße, Stadt, Land)",
    "checkingDistance": "Entfernung wird geprüft...",
    "fromKirchheim": "von Kirchheim",
    "technologies": "Technologien",
    "techPlaceholder": "Tech eingeben und Enter drücken (z.B. Java, React)",
    "buyTemplate": "Diese Website-Vorlage kaufen",
    "buyTemplateMessage": "Diese Vorlage wurde entwickelt, um Ihre LinkedIn-Daten einfach zu importieren. Ich sende Ihnen die Einrichtungsanweisungen!",
    "recruitingCompany": "Recruiting (Meine Firma)",
    "recruitingClient": "Recruiting (Für einen Kunden)",
    "personalProject": "Persönliches Projekt / Freelance",
    "techError": "Ich akzeptiere keine Projekte mit {tech}. Ich spezialisiere mich auf Java/Spring & JS/React Ökosysteme.",
    "distanceError": "Entfernung ist {distance}km. Ich akzeptiere nur Vor-Ort-Angebote innerhalb von 25km, Umzug ist keine Option, innerhalb Deutschlands.",
    "addressNotFound": "Konnte diese Adresse nicht finden. Bitte seien Sie genauer.",
    "addressError": "Fehler bei der Standortprüfung. Bitte versuchen Sie es erneut.",
    "addressRequired": "Adresse ist für Vor-Ort/Hybrid-Angebote erforderlich.",
    "successMessage": "Vielen Dank!",
    "emailSent": "E-Mail gesendet",
    "notContacted": "Noch nicht kontaktiert",
    "results": "Ergebnisse",
    institutionLabel: "institution=",
    degreeLabel: "abschluss=",
    yearLabel: "jahr=",
    locationLabel: "ort=",
    companyLabel: "firma=",
    timeLabel: "zeit=",
    typeLabel: "typ=",
    sizeLabel: "größe=",
    educationLabel: "ausbildung=",
    showDetails: "Details anzeigen",
    showLess: "Weniger anzeigen",
    cooldownMessage: "Sie können eine weitere Nachricht senden in",
    sendAnother: "Weitere Nachricht senden",
    errorMessage: "Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie mich direkt per E-Mail.",
    mainBranch: "main*",
    portfolioLabel: "PORTFOLIO",
    viewProfile: "Profil ansehen",
    connections: "Kontakte",
    readMore: "Mehr lesen",
    topSkills: "Top Fähigkeiten",
    certificationsLabel: "Zertifizierungen",
    joined: "Beigetreten",
    repositories: "Repositories",
    contributions: "Beiträge (Letztes Jahr)",
    achievements: "Erfolge",
    loadingGithub: "GitHub-Profil wird geladen...",
    errorGithub: "GitHub-Profil konnte nicht geladen werden",
    portfolioTitle: "Portfolio - Antigravity - liviuionesi.dev",
    lnCol: "Zl 1, Sp 1",
    utf8: "UTF-8",
    zoom: "100%",
    viewCode: "Code anzeigen",
    liveDemo: "Live-Demo",
    stackLabel: "stack=",
    loading: "Laden...",
    error: "Fehler",
    aboutFile: "UberMich.tsx",
    experienceFile: "Erfahrung.java",
    educationFile: "Ausbildung.tsx",
    projectsFile: "Projekte.json",
    contactFile: "Kontakt.tsx",
    quickDraw: "Quick Draw",
    pullShark: "Pull Shark",
    yolo: "YOLO",
    srcFolder: "src",
    cvGenerator: "CV-Generator",
    cvConfig: "CV Konfiguration",
    contentDetail: "Inhalt Detail",
    briefSummary: "Kurze Zusammenfassung",
    detailedView: "Detaillierte Ansicht",
    sections: "Abschnitte",
    includeProjects: "Projekte einbeziehen",
    visualStyle: "Visueller Stil",
    printOptimized: "Druckoptimiert",
    ideTheme: "IDE Design",
    openPrintableCV: "Druckversion öffnen",
    briefSummaryDesc: "Kompakte Ansicht nur mit Zusammenfassungen. Am besten zum schnellen Überfliegen.",
    detailedViewDesc: "Enthält vollständige Berufsbiografie und komplette Stellenbeschreibungen.",
    printOptimizedDesc: "Sauberer weißer Hintergrund, optimiert für den physischen Druck.",
    ideThemeDesc: "Verwendet das dunkle Design des Portfolios. Am besten zum Teilen als PDF.",
    openInNewTabDesc: "Öffnet in neuem Tab. Verwenden Sie den Druckdialog (Strg+P), um als PDF zu speichern.",
  },
  ro: {
    "getInTouch": "Contactează-mă",
    "contactIntro": "Fie că ai o întrebare, o propunere de proiect sau vrei doar să saluți, voi încerca să-ți răspund cât mai repede!",
    "name": "Nume",
    "email": "Email",
    "subject": "Subiect",
    "message": "Mesaj",
    "sendMessage": "Trimite Mesaj",
    "sending": "Se trimite...",
    "projects": "Proiecte",
    "experience": "Experiență Profesională",
    "education": "Educație",
    "about": "Despre Mine",
    "contact": "Contact",
    "explorer": "Explorator",
    "search": "Căutare",
    "searchPlaceholder": "Caută (Ctrl+Shift+F)",
    "clearSearch": "Șterge Căutarea",
    "noResults": "Niciun rezultat pentru",
    "githubStats": "Statistici GitHub",
    "linkedinProfile": "Profil LinkedIn",
    "resume": "CV",
    "viewResume": "Vezi CV",
    "downloadResume": "Descarcă CV",
    "allRightsReserved": "Toate drepturile rezervate",
    "builtWith": "Construit cu",
    "and": "și",
    "biography": "Biografie",
    "contactMe": "Contactează-mă",
    "switchLanguage": "Schimbă Limba",
    "switchTheme": "Schimbă Tema",
    "settings": "Setări",
    "phoneOptional": "Telefon (Opțional)",
    "purpose": "Scop",
    "locationPreference": "Preferință Locație",
    "remote": "Remote",
    "hybrid": "Hibrid",
    "onsite": "La sediu",
    "addressLabel": "Adresă pentru calcul distanță",
    "officeAddressPlaceholder": "Adresă Birou (Stradă, Oraș, Țară)",
    "checkingDistance": "Se verifică distanța...",
    "fromKirchheim": "de Kirchheim",
    "technologies": "Tehnologii",
    "techPlaceholder": "Scrie tech și apasă Enter (ex. Java, React)",
    "buyTemplate": "Cumpără acest șablon de site",
    "buyTemplateMessage": "Acest șablon este conceput pentru a importa  datele din profilul de LinkedIn. Îți voi trimite instrucțiunile de configurare!",
    "recruitingCompany": "Recrutare (Compania mea)",
    "recruitingClient": "Recrutare (Pentru un client)",
    "personalProject": "Proiect Personal / Freelance",
    "techError": "Nu accept proiecte care implică {tech}. Sunt specializat în ecosistemele Java/Spring & JS/React/Next.js.",
    "distanceError": "Distanța este {distance}km. Accept doar oferte la sediu pe o rază de 25km, Relocarea nu este posibilă în Germania.",
    "addressNotFound": "Nu am putut găsi această adresă. Te rog să fii mai specific.",
    "addressError": "Eroare la verificarea locației. Te rog încearcă din nou.",
    "addressRequired": "Adresa este necesară pentru ofertele la sediu/hibrid.",
    "successMessage": "Mulțumesc!",
    "emailSent": "Email trimis",
    "notContacted": "Necontactat",
    "results": "rezultate",
    institutionLabel: "instituție=",
    degreeLabel: "diplomă=",
    yearLabel: "an=",
    locationLabel: "locație=",
    companyLabel: "companie=",
    timeLabel: "timp=",
    typeLabel: "tip=",
    sizeLabel: "mărime=",
    educationLabel: "educație=",
    showDetails: "Mai mult",
    showLess: "Mai puțin",
    cooldownMessage: "Poți trimite un alt mesaj în",
    sendAnother: "Trimite un alt mesaj",
    errorMessage: "Nu s-a putut trimite mesajul. Te rog încearcă din nou mai târziu, sau contactează-mă direct prin email.",
    mainBranch: "main*",
    portfolioLabel: "PORTFOLIO",
    viewProfile: "Vezi Profil",
    connections: "conexiuni",
    readMore: "Citește Mai Mult",
    topSkills: "Abilități de Top",
    certificationsLabel: "Certificări",
    joined: "S-a alăturat",
    repositories: "Proiecte",
    contributions: "Contribuții (anul trecut)",
    achievements: "Medalii",
    loadingGithub: "Se încarcă profilul GitHub...",
    errorGithub: "Nu s-a putut încărca profilul GitHub",
    portfolioTitle: "portofoliu - Antigravity - liviuionesi.dev",
    lnCol: "Ln 1, Col 1",
    utf8: "UTF-8",
    zoom: "100%",
    viewCode: "Vezi Cod",
    liveDemo: "Demo Live",
    stackLabel: "stack=",
    loading: "Se încarcă...",
    error: "Eroare",
    aboutFile: "DespreMine.tsx",
    experienceFile: "Experienta.java",
    educationFile: "Educatie.tsx",
    projectsFile: "Proiecte.json",
    contactFile: "Contact.tsx",
    quickDraw: "Quick Draw",
    pullShark: "Pull Shark",
    yolo: "YOLO",
    srcFolder: "src",
    cvConfig: "Configurare CV",
    contentDetail: "Detaliu Conținut",
    briefSummary: "Rezumat Scurt",
    detailedView: "Vizualizare Detaliată",
    sections: "Secțiuni",
    includeProjects: "Include Proiecte",
    visualStyle: "Stil Vizual",
    printOptimized: "Optimizat pentru Print",
    ideTheme: "Temă IDE",
    openPrintableCV: "Deschide Versiune Printabilă",
    briefSummaryDesc: "Vizualizare compactă doar cu rezumate. Ideal pentru scanare rapidă.",
    detailedViewDesc: "Include biografia profesională completă și descrierile joburilor.",
    printOptimizedDesc: "Fundal alb curat, optimizat pentru imprimare fizică.",
    ideThemeDesc: "Folosește tema întunecată a portofoliului. Ideal pentru partajare PDF.",
    openInNewTabDesc: "Se deschide în tab nou. Folosește dialogul de printare (Ctrl+P) pentru a salva ca PDF.",
  },
  fr: {
    "getInTouch": "Contactez-moi",
    "contactIntro": "Que vous ayez une question, une proposition de projet ou juste pour dire bonjour, je ferai de mon mieux pour vous répondre !",
    "name": "Nom",
    "email": "Email",
    "subject": "Sujet",
    "message": "Message",
    "sendMessage": "Envoyer le message",
    "sending": "Envoi...",
    "projects": "Projets",
    "experience": "Expérience Professionnelle",
    "education": "Éducation",
    "about": "À Propos",
    "contact": "Contact",
    "explorer": "Explorateur",
    "search": "Recherche",
    "searchPlaceholder": "Rechercher (Ctrl+Shift+F)",
    "clearSearch": "Effacer la recherche",
    "noResults": "Aucun résultat pour",
    "githubStats": "Stats GitHub",
    "linkedinProfile": "Profil LinkedIn",
    "resume": "CV",
    "viewResume": "Voir CV",
    "downloadResume": "Télécharger CV",
    "allRightsReserved": "Tous droits réservés",
    "builtWith": "Construit avec",
    "and": "et",
    "biography": "Biographie",
    "contactMe": "Contactez-moi",
    "switchLanguage": "Changer de langue",
    "switchTheme": "Changer de thème",
    "settings": "Paramètres",
    "phoneOptional": "Téléphone (Optionnel)",
    "purpose": "Objet",
    "locationPreference": "Préférence de localisation",
    "remote": "Télétravail",
    "hybrid": "Hybride",
    "onsite": "Sur site",
    "addressLabel": "Adresse pour le calcul de la distance",
    "officeAddressPlaceholder": "Adresse du bureau (Rue, Ville, Pays)",
    "checkingDistance": "Vérification de la distance...",
    "fromKirchheim": "de Kirchheim",
    "technologies": "Technologies",
    "techPlaceholder": "Tapez tech et appuyez sur Entrée (ex: Java, React)",
    "buyTemplate": "Acheter ce modèle de site",
    "buyTemplateMessage": "Ce modèle est conçu pour importer facilement vos données LinkedIn. Je vous enverrai les instructions d'installation !",
    "recruitingCompany": "Recrutement (Mon entreprise)",
    "recruitingClient": "Recrutement (Pour un client)",
    "personalProject": "Projet Personnel / Freelance",
    "techError": "Je n'accepte pas de projets impliquant {tech}. Je me spécialise dans les écosystèmes Java/Spring & JS/React.",
    "distanceError": "La distance est de {distance}km. J'accepte uniquement les offres sur site dans un rayon de 25km, le déménagement n'est pas une option, en Allemagne.",
    "addressNotFound": "Impossible de trouver cette adresse. Veuillez être plus précis.",
    "addressError": "Erreur lors de la vérification de la localisation. Veuillez réessayer.",
    "addressRequired": "L'adresse est requise pour les offres sur site/hybrides.",
    "successMessage": "Merci !",
    "emailSent": "Email Envoyé",
    "notContacted": "Pas encore contacté",
    "results": "résultats",
    institutionLabel: "institution=",
    degreeLabel: "diplôme=",
    yearLabel: "année=",
    locationLabel: "lieu=",
    companyLabel: "entreprise=",
    timeLabel: "temps=",
    typeLabel: "type=",
    sizeLabel: "taille=",
    educationLabel: "éducation=",
    showDetails: "Voir Détails",
    showLess: "Voir Moins",
    cooldownMessage: "Vous pouvez envoyer un autre message dans",
    sendAnother: "Envoyer un autre message",
    errorMessage: "Échec de l'envoi du message. Veuillez réessayer plus tard ou contactez-moi directement par email.",
    mainBranch: "main*",
    portfolioLabel: "PORTFOLIO",
    viewProfile: "Voir Profil",
    connections: "connexions",
    readMore: "Lire Plus",
    topSkills: "Compétences Principales",
    certificationsLabel: "Certifications",
    joined: "Rejoint",
    repositories: "Dépôts",
    contributions: "Contributions (Année Dernière)",
    achievements: "Réalisations",
    loadingGithub: "Chargement du profil GitHub...",
    errorGithub: "Impossible de charger le profil GitHub",
    portfolioTitle: "portfolio - Antigravity - liviuionesi.dev",
    lnCol: "Ln 1, Col 1",
    utf8: "UTF-8",
    zoom: "100%",
    viewCode: "Voir Code",
    liveDemo: "Démo Live",
    stackLabel: "stack=",
    loading: "Chargement...",
    error: "Erreur",
    aboutFile: "APropos.tsx",
    experienceFile: "Experience.java",
    educationFile: "Education.tsx",
    projectsFile: "Projets.json",
    contactFile: "Contact.tsx",
    quickDraw: "Dégaineur",
    pullShark: "Pull Shark",
    yolo: "YOLO",
    srcFolder: "src",
    cvConfig: "Configuration CV",
    contentDetail: "Détail du Contenu",
    briefSummary: "Un Bref Résumé",
    detailedView: "Vue Détaillée",
    sections: "Sections",
    includeProjects: "Inclure Projets",
    visualStyle: "Style Visuel",
    printOptimized: "Optimisé pour l'Impression",
    ideTheme: "Thème IDE",
    openPrintableCV: "Ouvrir Version Imprimable",
    briefSummaryDesc: "Vue compacte avec résumés uniquement. Idéal pour une lecture rapide.",
    detailedViewDesc: "Inclut la biographie professionnelle complète et les descriptions de poste.",
    printOptimizedDesc: "Fond blanc propre, optimisé pour l'impression physique.",
    ideThemeDesc: "Utilise le thème sombre du portfolio. Idéal pour le partage PDF.",
    openInNewTabDesc: "S'ouvre dans un nouvel onglet. Utilisez la boîte de dialogue d'impression (Ctrl+P) pour enregistrer en PDF.",
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, data: dataMap[language], t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
