'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';
import * as enData from '@/data/mockData';
import * as deData from '@/data/mockDataDe';
import * as roData from '@/data/mockDataRo';
import * as frData from '@/data/mockDataFr';

export type Language = 'en' | 'de' | 'ro' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  data: typeof enData;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const dataMap = {
  en: enData,
  de: deData,
  ro: roData,
  fr: frData,
};

export const translations: Record<Language, Record<string, string>> = {
  en: {
    getInTouch: 'Get In Touch',
    contactIntro:
      "Whether you have a question, a project proposal, or just want to say hi, I'll try my best to get back to you!",
    name: 'Name',
    email: 'Email',
    subject: 'Subject',
    message: 'Message',
    sendMessage: 'Send message',
    sending: 'Sending...',
    projects: 'Projects',
    experience: 'Work experience',
    education: 'Education',
    about: 'About me',
    contact: 'Contact me',
    explorer: 'Explorer',
    search: 'Search',
    searchPlaceholder: 'Search (Ctrl+Shift+F)',
    clearSearch: 'Clear search',
    noResults: 'No results found for',
    linkedinProfile: 'LinkedIn Profile',
    resume: 'Resume',
    viewResume: 'View resume',
    downloadResume: 'Download resume',
    allRightsReserved: 'All rights reserved',
    builtWith: 'Built with',
    and: 'and',
    biography: 'Biography',
    contactMe: 'Contact me',
    switchLanguage: 'Switch language',
    switchTheme: 'Switch theme',
    settings: 'Settings',
    phoneOptional: 'Phone (optional)',
    purpose: 'Purpose',
    locationPreference: 'Location preference',
    remote: 'Remote',
    hybrid: 'Hybrid',
    onsite: 'On-site',
    addressLabel: 'Address for distance calculation',
    officeAddressPlaceholder: 'Office Address (Street, City, Country)',
    checkingDistance: 'Checking distance...',
    fromKirchheim: 'from Kirchheim',
    technologies: 'Technologies',
    techPlaceholder: 'Type tech and press Enter (e.g. Java, React)',
    buyTemplate: 'Buy this website template',
    buyTemplateMessage:
      "This template is designed to easily import your LinkedIn data. I'll send you the setup instructions!",
    recruitingCompany: 'Recruiting (my company)',
    recruitingClient: 'Recruiting (for a client)',
    personalProject: 'Personal project / Freelance',
    techError:
      'I do not accept projects involving {tech}. I specialize in Java/Spring & JS/React ecosystems.',
    distanceError:
      'Travel time is approx. {time} min. I generally accept on-site offers within 1 hour travel time. Relocation is not an option (inside Germany).',
    addressNotFound: 'Could not find this address. Please try to be more specific.',
    addressError: 'Error checking location. Please try again.',
    addressRequired: 'Address is required for on-site/hybrid offers.',
    successMessage: 'Thank you!',
    emailSent: 'Email Sent',
    notContacted: 'Not Contacted Yet',
    results: 'results',
    institutionLabel: 'institution=',
    degreeLabel: 'degree=',
    yearLabel: 'year=',
    locationLabel: 'location=',
    companyLabel: 'company=',
    timeLabel: 'time=',
    typeLabel: 'type=',
    sizeLabel: 'size=',
    educationLabel: 'education=',
    showDetails: 'More',
    showLess: 'Less',
    cooldownMessage: 'You can send another message in',
    sendAnother: 'Send another message',
    errorMessage:
      'Failed to send message. Please try again later or contact me directly via email.',
    mainBranch: 'main*',
    portfolioLabel: 'PORTFOLIO',
    viewProfile: 'View Profile',
    connections: 'connections',
    readMore: 'More',
    topSkills: 'Top Skills',
    certificationsLabel: 'Certifications',
    joined: 'Joined',
    repositories: 'Repositories',
    contributions: 'Contributions (Last Year)',
    achievements: 'Achievements',
    loadingGithub: 'Loading GitHub Profile...',
    errorGithub: 'Could not load GitHub profile',
    portfolioTitle: 'portfolio - Antigravity - liviuionesi.com',
    lnCol: 'Ln 1, Col 1',
    utf8: 'UTF-8',
    zoom: '100%',
    viewCode: 'View Code',
    liveDemo: 'Live Demo',
    stackLabel: 'stack=',
    loading: 'Loading...',
    error: 'Error',
    aboutFile: 'About.tsx',
    experienceFile: 'Experience.java',
    educationFile: 'Education.tsx',
    projectsFile: 'Projects.json',
    contactFile: 'Contact.tsx',
    quickDraw: 'Quick Draw',
    pullShark: 'Pull Shark',
    yolo: 'YOLO',
    srcFolder: 'src',
    cvGenerator: 'CV Generator',
    cvConfig: 'CV Configuration',
    contentDetail: 'Content detail',
    briefSummary: 'Brief summary',
    detailedView: 'Detailed view',
    sections: 'Sections',
    includeProjects: 'Include projects',
    visualStyle: 'Visual style',
    printOptimized: 'Print optimized',
    ideTheme: 'IDE theme',
    openPrintableCV: 'Print',
    briefSummaryDesc: 'Compact view with summaries only. Best for quick scanning.',
    detailedViewDesc: 'Includes full professional biography and complete job descriptions.',
    printOptimizedDesc: 'Clean white background, optimized for physical paper printing.',
    ideThemeDesc: "Uses the portfolio's dark theme. Best for PDF sharing.",
    openInNewTabDesc:
      "Opens in a new tab. Use your browser's print dialog (Ctrl+P) to save as PDF.",
    cvProfessionalSummary: 'Professional Summary',
    cvTechnicalSkills: 'Technical Skills',
    cvProfessionalExperience: 'Professional Experience',
    cvProjects: 'Projects',
    cvEducation: 'Education',
    cvCertifications: 'Certifications',
    cvLanguages: 'Languages',
    phone: 'Phone',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    atsFriendlyVersion: 'ATS-Friendly Version:',
    atsFriendlyDesc:
      'This layout is intentionally stripped of icons, complex layouts, and custom fonts. It uses pure semantic HTML (h1, h2, ul, li) to ensure maximum compatibility with Applicant Tracking Systems.',
    loadingAtsCv: 'Loading ATS CV...',
    loadingCv: 'Loading CV...',
    techLabel: 'Tech:',
    viewSource: 'View Source',
    viewLive: 'View Live',
    errorNoSleep: "Error: Developers don't sleep. You cannot close the IDE.",
    exit: 'Exit',
    exitFullscreen: 'Exit Fullscreen',
    enterFullscreen: 'Enter Fullscreen',
    systemShutdown: 'SYSTEM SHUTDOWN INITIATED...',
    rebootSystem: 'REBOOT SYSTEM',
  },
  de: {
    getInTouch: 'Kontakt aufnehmen',
    contactIntro:
      'Ob Sie eine Frage haben, einen Projektvorschlag oder einfach nur Hallo sagen wollen, ich werde mein Bestes geben, um Ihnen zu antworten!',
    name: 'Name',
    email: 'E-Mail',
    subject: 'Betreff',
    message: 'Nachricht',
    sendMessage: 'Nachricht senden',
    sending: 'Senden...',
    projects: 'Projekte',
    experience: 'Berufserfahrung',
    education: 'Ausbildung',
    about: 'Über mich',
    contact: 'Kontakt',
    explorer: 'Explorer',
    search: 'Suche',
    searchPlaceholder: 'Suchen (Ctrl+Shift+F)',
    clearSearch: 'Suche löschen',
    noResults: 'Keine Ergebnisse gefunden für',
    linkedinProfile: 'LinkedIn-Profil',
    resume: 'Lebenslauf',
    viewResume: 'Lebenslauf ansehen',
    downloadResume: 'Lebenslauf herunterladen',
    allRightsReserved: 'Alle Rechte vorbehalten',
    builtWith: 'Erstellt mit',
    and: 'und',
    biography: 'Biografie',
    contactMe: 'Kontaktieren Sie mich',
    switchLanguage: 'Sprache wechseln',
    switchTheme: 'Design wechseln',
    settings: 'Einstellungen',
    phoneOptional: 'Telefon (Optional)',
    purpose: 'Zweck',
    locationPreference: 'Standortpräferenz',
    remote: 'Remote',
    hybrid: 'Hybrid',
    onsite: 'Vor Ort',
    addressLabel: 'Adresse für Entfernungsberechnung',
    officeAddressPlaceholder: 'Büroadresse (Straße, Stadt, Land)',
    checkingDistance: 'Entfernung wird geprüft...',
    fromKirchheim: 'von Kirchheim',
    technologies: 'Technologien',
    techPlaceholder: 'Tech eingeben und Enter drücken (z.B. Java, React)',
    buyTemplate: 'Diese Website-Vorlage kaufen',
    buyTemplateMessage:
      'Diese Vorlage wurde entwickelt, um Ihre LinkedIn-Daten einfach zu importieren. Ich sende Ihnen die Einrichtungsanweisungen!',
    recruitingCompany: 'Recruiting (Meine Firma)',
    recruitingClient: 'Recruiting (Für einen Kunden)',
    personalProject: 'Persönliches Projekt / Freelance',
    techError:
      'Ich akzeptiere keine Projekte mit {tech}. Ich spezialisiere mich auf Java/Spring & JS/React Ökosysteme.',
    distanceError:
      'Reisezeit beträgt ca. {time} Min. Ich akzeptiere grundsätzlich Vor-Ort-Angebote innerhalb von 1 Stunde Reisezeit. Umzug ist keine Option (innerhalb Deutschlands).',
    addressNotFound: 'Konnte diese Adresse nicht finden. Bitte seien Sie genauer.',
    addressError: 'Fehler bei der Standortprüfung. Bitte versuchen Sie es erneut.',
    addressRequired: 'Adresse ist für Vor-Ort/Hybrid-Angebote erforderlich.',
    successMessage: 'Vielen Dank!',
    emailSent: 'E-Mail gesendet',
    notContacted: 'Noch nicht kontaktiert',
    results: 'Ergebnisse',
    institutionLabel: 'institution=',
    degreeLabel: 'abschluss=',
    yearLabel: 'jahr=',
    locationLabel: 'ort=',
    companyLabel: 'firma=',
    timeLabel: 'zeit=',
    typeLabel: 'typ=',
    sizeLabel: 'größe=',
    educationLabel: 'ausbildung=',
    showDetails: 'Mehr',
    showLess: 'Weniger',
    cooldownMessage: 'Sie können eine weitere Nachricht senden in',
    sendAnother: 'Weitere Nachricht senden',
    errorMessage:
      'Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie mich direkt per E-Mail.',
    mainBranch: 'main*',
    portfolioLabel: 'PORTFOLIO',
    viewProfile: 'Profil ansehen',
    connections: 'Kontakte',
    readMore: 'Mehr',
    topSkills: 'Top Fähigkeiten',
    certificationsLabel: 'Zertifizierungen',
    joined: 'Beigetreten',
    repositories: 'Repositories',
    contributions: 'Beiträge (letztes Jahr)',
    achievements: 'Erfolge',
    loadingGithub: 'GitHub-Profil wird geladen...',
    errorGithub: 'GitHub-Profil konnte nicht geladen werden',
    portfolioTitle: 'Portfolio - Antigravity - liviuionesi.com',
    lnCol: 'Zl 1, Sp 1',
    utf8: 'UTF-8',
    zoom: '100%',
    viewCode: 'Code anzeigen',
    liveDemo: 'Live-Demo',
    stackLabel: 'stack=',
    loading: 'Laden...',
    error: 'Fehler',
    aboutFile: 'UberMich.tsx',
    experienceFile: 'Erfahrung.java',
    educationFile: 'Ausbildung.tsx',
    projectsFile: 'Projekte.json',
    contactFile: 'Kontakt.tsx',
    quickDraw: 'Quick Draw',
    pullShark: 'Pull Shark',
    yolo: 'YOLO',
    srcFolder: 'src',
    cvGenerator: 'CV-Generator',
    cvConfig: 'CV Konfiguration',
    contentDetail: 'Inhalt Detail',
    briefSummary: 'Kurze Zusammenfassung',
    detailedView: 'Detaillierte Ansicht',
    sections: 'Abschnitte',
    includeProjects: 'Projekte einbeziehen',
    visualStyle: 'Visueller Stil',
    printOptimized: 'Druckoptimiert',
    ideTheme: 'IDE Design',
    openPrintableCV: 'Drucken',
    briefSummaryDesc:
      'Kompakte Ansicht nur mit Zusammenfassungen. Am besten zum schnellen Überfliegen.',
    detailedViewDesc: 'Enthält vollständige Berufsbiografie und komplette Stellenbeschreibungen.',
    printOptimizedDesc: 'Sauberer weißer Hintergrund, optimiert für den physischen Druck.',
    ideThemeDesc: 'Verwendet das dunkle Design des Portfolios. Am besten zum Teilen als PDF.',
    openInNewTabDesc:
      'Öffnet sich in einem neuen Tab. Verwenden Sie den Druckdialog (Strg+P), um als PDF zu speichern.',
    cvProfessionalSummary: 'Berufliches Profil',
    cvTechnicalSkills: 'Technische Fähigkeiten',
    cvProfessionalExperience: 'Berufserfahrung',
    cvProjects: 'Projekte',
    cvEducation: 'Ausbildung',
    cvCertifications: 'Zertifizierungen',
    cvLanguages: 'Sprachen',
    phone: 'Telefon',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    atsFriendlyVersion: 'ATS-freundliche Version:',
    atsFriendlyDesc:
      'Dieses Layout verzichtet absichtlich auf Symbole, komplexe Layouts und benutzerdefinierte Schriftarten. Es verwendet reines semantisches HTML (h1, h2, ul, li), um maximale Kompatibilität mit Bewerbermanagementsystemen (ATS) zu gewährleisten.',
    loadingAtsCv: 'Lade ATS Lebenslauf...',
    loadingCv: 'Lade Lebenslauf...',
    techLabel: 'Technologien:',
    viewSource: 'Quellcode anzeigen',
    viewLive: 'Live-Demo anzeigen',
    errorNoSleep: 'Fehler: Entwickler schlafen nicht. Sie können die IDE nicht schließen.',
    exit: 'Beenden',
    exitFullscreen: 'Vollbild beenden',
    enterFullscreen: 'Vollbild',
    systemShutdown: 'SYSTEM-SHUTDOWN EINGELEITET...',
    rebootSystem: 'SYSTEM NEUSTARTEN',
  },
  ro: {
    getInTouch: 'Contactează-mă',
    contactIntro:
      'Fie că ai o întrebare, o propunere de proiect sau vrei doar să mă saluți, voi încerca să-ți răspund cât mai repede!',
    name: 'Nume',
    email: 'E-mail',
    subject: 'Subiect',
    message: 'Mesaj',
    sendMessage: 'Trimite mesaj',
    sending: 'Se trimite...',
    projects: 'Proiecte',
    experience: 'Experiență profesională',
    education: 'Educație',
    about: 'Despre mine',
    contact: 'Contact',
    explorer: 'Explorator',
    search: 'Căutare',
    searchPlaceholder: 'Caută (Ctrl+Shift+F)',
    clearSearch: 'Șterge căutarea',
    noResults: 'Niciun rezultat pentru',
    linkedinProfile: 'Profil LinkedIn',
    resume: 'CV',
    viewResume: 'Vezi CV',
    downloadResume: 'Descarcă CV',
    allRightsReserved: 'Toate drepturile rezervate',
    builtWith: 'Construit cu',
    and: 'și',
    biography: 'Biografie',
    contactMe: 'Contactează-mă',
    switchLanguage: 'Schimbă limba',
    switchTheme: 'Schimbă tema',
    settings: 'Setări',
    phoneOptional: 'Telefon (opțional)',
    purpose: 'Scop',
    locationPreference: 'Preferință locație',
    remote: 'Remote',
    hybrid: 'Hibrid',
    onsite: 'La sediu',
    addressLabel: 'Adresă pentru calcul distanță',
    officeAddressPlaceholder: 'Adresă birou (stradă, oraș, țară)',
    checkingDistance: 'Se verifică distanța...',
    fromKirchheim: 'de Kirchheim',
    technologies: 'Tehnologii',
    techPlaceholder: 'Adaugă tehnologia și apasă Enter (ex. Java, React)',
    buyTemplate: 'Cumpără acest site',
    buyTemplateMessage:
      'Acest site este conceput pentru a importa  datele din profilul de LinkedIn. Îți voi trimite instrucțiunile de configurare!',
    recruitingCompany: 'Recrutare (compania mea)',
    recruitingClient: 'Recrutare (pentru un client)',
    personalProject: 'Proiect personal / Freelance',
    techError:
      'Nu accept proiecte care implică {tech}. Sunt specializat în ecosistemele Java/Spring & JS/React/Next.js.',
    distanceError:
      'Timpul de călătorie este de aprox. {time} min. Accept în general oferte on-site cu un timp de călătorie de maxim 1 oră. Relocarea nu este o opțiune (în Germania).',
    addressNotFound: 'Nu am putut găsi această adresă. Te rog să fii mai specific.',
    addressError: 'Eroare la verificarea locației. Te rog încearcă din nou.',
    addressRequired: 'Adresa este necesară pentru ofertele la sediu/hibrid.',
    successMessage: 'Mulțumesc!',
    emailSent: 'E-mail trimis',
    notContacted: 'Necontactat',
    results: 'rezultate',
    institutionLabel: 'instituție=',
    degreeLabel: 'diplomă=',
    yearLabel: 'an=',
    locationLabel: 'locație=',
    companyLabel: 'companie=',
    timeLabel: 'perioadă=',
    typeLabel: 'tip=',
    sizeLabel: 'mărime=',
    educationLabel: 'educație=',
    showDetails: 'Mai mult',
    showLess: 'Mai puțin',
    cooldownMessage: 'Poți trimite un alt mesaj în',
    sendAnother: 'Trimite un alt mesaj',
    errorMessage:
      'Nu s-a putut trimite mesajul. Te rog, încearcă din nou mai târziu, sau contactează-mă direct prin e-mail.',
    mainBranch: 'main*',
    portfolioLabel: 'PORTFOLIO',
    viewProfile: 'Vezi profil',
    connections: 'conexiuni',
    readMore: 'Mai mult',
    topSkills: 'Abilități',
    certificationsLabel: 'Certificări',
    joined: 'S-a alăturat',
    repositories: 'Proiecte',
    contributions: 'Contribuții (în anul trecut)',
    achievements: 'Medalii',
    loadingGithub: 'Se încarcă profilul de GitHub...',
    errorGithub: 'Nu s-a putut încărca profilul de GitHub',
    portfolioTitle: 'portofoliu - Antigravity - liviuionesi.com',
    lnCol: 'Ln 1, Col 1',
    utf8: 'UTF-8',
    zoom: '100%',
    viewCode: 'Vezi cod',
    liveDemo: 'Demo live',
    stackLabel: 'stack=',
    loading: 'Se încarcă...',
    error: 'Eroare',
    aboutFile: 'DespreMine.tsx',
    experienceFile: 'Experienta.java',
    educationFile: 'Educatie.tsx',
    projectsFile: 'Proiecte.json',
    contactFile: 'Contact.tsx',
    quickDraw: 'Quick Draw',
    pullShark: 'Pull Shark',
    yolo: 'YOLO',
    srcFolder: 'src',
    cvConfig: 'Configurare CV',
    contentDetail: 'Detaliu conținut',
    briefSummary: 'Rezumat scurt',
    detailedView: 'Vizualizare detaliată',
    sections: 'Secțiuni',
    includeProjects: 'Include proiecte',
    visualStyle: 'Stil vizual',
    printOptimized: 'Optimizat pentru print',
    ideTheme: 'Temă IDE',
    openPrintableCV: 'Printează',
    briefSummaryDesc: 'Vizualizare a versiunii compacte. Ideal pentru scanare rapidă.',
    detailedViewDesc: 'Include biografia profesională completă și descrierile joburilor.',
    printOptimizedDesc: 'Fundal alb curat, optimizat pentru imprimare.',
    ideThemeDesc: 'Folosește tema întunecată a portofoliului. Ideal pentru partajare PDF.',
    openInNewTabDesc:
      'Se deschide într-o filă nouă. Folosiți dialogul de imprimare (Ctrl+P) pentru a salva ca PDF.',
    cvProfessionalSummary: 'Rezumat Profesional',
    cvTechnicalSkills: 'Abilități Tehnice',
    cvProfessionalExperience: 'Experiență Profesională',
    cvProjects: 'Proiecte',
    cvEducation: 'Educație',
    cvCertifications: 'Certificări',
    cvLanguages: 'Limbi Străine',
    phone: 'Telefon',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    atsFriendlyVersion: 'Versiune ATS-Friendly:',
    atsFriendlyDesc:
      'Acest layout a fost curățat intenționat de pictograme, layout-uri complexe și fonturi personalizate. Folosește exclusiv HTML semantic (h1, h2, ul, li) pentru a asigura compatibilitatea maximă cu Sistemele de Urmărire a Aplicanților (ATS).',
    loadingAtsCv: 'Se încarcă CV-ul ATS...',
    loadingCv: 'Se încarcă CV-ul...',
    techLabel: 'Tehnologii:',
    viewSource: 'Vezi codul sursă',
    viewLive: 'Vezi demo-ul',
    errorNoSleep: 'Eroare: Dezvoltatorii nu dorm. Nu poți închide IDE-ul.',
    exit: 'Ieșire',
    exitFullscreen: 'Ieșire ecran complet',
    enterFullscreen: 'Ecran complet',
    systemShutdown: 'OPRIRE SISTEM INIȚIATĂ...',
    rebootSystem: 'REPORNIRE SISTEM',
  },
  fr: {
    getInTouch: 'Contactez-moi',
    contactIntro:
      'Que vous ayez une question, une proposition de projet ou juste pour dire bonjour, je ferai de mon mieux pour vous répondre !',
    name: 'Nom',
    email: 'Email',
    subject: 'Sujet',
    message: 'Message',
    sendMessage: 'Envoyer le message',
    sending: 'Envoi...',
    projects: 'Projets',
    experience: 'Expérience professionnelle',
    education: 'Éducation',
    about: 'À propos',
    contact: 'Contact',
    explorer: 'Explorateur',
    search: 'Recherche',
    searchPlaceholder: 'Rechercher (Ctrl+Shift+F)',
    clearSearch: 'Effacer la recherche',
    noResults: 'Aucun résultat pour',
    linkedinProfile: 'Profil LinkedIn',
    resume: 'CV',
    viewResume: 'Voir CV',
    downloadResume: 'Télécharger CV',
    allRightsReserved: 'Tous droits réservés',
    builtWith: 'Construit avec',
    and: 'et',
    biography: 'Biographie',
    contactMe: 'Contactez-moi',
    switchLanguage: 'Changer de langue',
    switchTheme: 'Changer de thème',
    settings: 'Paramètres',
    phoneOptional: 'Téléphone (optionnel)',
    purpose: 'Objet',
    locationPreference: 'Préférence de localisation',
    remote: 'Télétravail',
    hybrid: 'Hybride',
    onsite: 'Sur site',
    addressLabel: 'Adresse pour le calcul de la distance',
    officeAddressPlaceholder: 'Adresse du bureau (Rue, Ville, Pays)',
    checkingDistance: 'Vérification de la distance...',
    fromKirchheim: 'de Kirchheim',
    technologies: 'Technologies',
    techPlaceholder: 'Tapez tech et appuyez sur Entrée (ex: Java, React)',
    buyTemplate: 'Acheter ce modèle de site',
    buyTemplateMessage:
      "Ce modèle est conçu pour importer facilement vos données LinkedIn. Je vous enverrai les instructions d'installation !",
    recruitingCompany: 'Recrutement (mon entreprise)',
    recruitingClient: 'Recrutement (pour un client)',
    personalProject: 'Projet personnel / Freelance',
    techError:
      "Je n'accepte pas de projets impliquant {tech}. Je me spécialise dans les écosystèmes Java/Spring & JS/React.",
    distanceError:
      "Le temps de trajet est d'env. {time} min. J'accepte généralement les offres sur site avec un temps de trajet de 1 heure maximum. Le déménagement n'est pas une option (en Allemagne).",
    addressNotFound: 'Impossible de trouver cette adresse. Veuillez être plus précis.',
    addressError: 'Erreur lors de la vérification de la localisation. Veuillez réessayer.',
    addressRequired: "L'adresse est requise pour les offres sur site/hybrides.",
    successMessage: 'Merci !',
    emailSent: 'Email envoyé',
    notContacted: 'Pas encore contacté',
    institutionLabel: 'institution=',
    degreeLabel: 'diplôme=',
    yearLabel: 'année=',
    locationLabel: 'lieu=',
    companyLabel: 'entreprise=',
    timeLabel: 'temps=',
    typeLabel: 'type=',
    sizeLabel: 'taille=',
    educationLabel: 'éducation=',
    showDetails: 'Plus',
    showLess: 'Moins',
    cooldownMessage: 'Vous pouvez envoyer un autre message dans',
    sendAnother: 'Envoyer un autre message',
    errorMessage:
      "Échec de l'envoi du message. Veuillez réessayer plus tard ou contactez-moi directement par email.",
    mainBranch: 'main*',
    portfolioLabel: 'PORTFOLIO',
    viewProfile: 'Voir profil',
    connections: 'connexions',
    readMore: 'Plus',
    topSkills: 'Compétences',
    certificationsLabel: 'Certifications',
    joined: 'Rejoint',
    repositories: 'Dépôts',
    contributions: 'Contributions (année dernière)',
    achievements: 'Réalisations',
    loadingGithub: 'Chargement du profil GitHub...',
    errorGithub: 'Impossible de charger le profil GitHub',
    portfolioTitle: 'portfolio - Antigravity - liviuionesi.com',
    lnCol: 'Ln 1, Col 1',
    utf8: 'UTF-8',
    zoom: '100%',
    viewCode: 'Voir Code',
    liveDemo: 'Démo Live',
    stackLabel: 'stack=',
    loading: 'Chargement...',
    error: 'Erreur',
    aboutFile: 'APropos.tsx',
    experienceFile: 'Experience.java',
    educationFile: 'Education.tsx',
    projectsFile: 'Projets.json',
    contactFile: 'Contact.tsx',
    quickDraw: 'Dégaineur',
    pullShark: 'Pull Shark',
    yolo: 'YOLO',
    srcFolder: 'src',
    cvConfig: 'Configuration CV',
    contentDetail: 'Détail du contenu',
    briefSummary: 'Un bref résumé',
    detailedView: 'Vue détaillée',
    sections: 'Sections',
    includeProjects: 'Inclure projets',
    visualStyle: 'Style visuel',
    printOptimized: "Optimisé pour l'imprimer",
    ideTheme: 'Thème IDE',
    openPrintableCV: 'Imprimer',
    briefSummaryDesc: 'Vue compacte avec résumés uniquement. Idéal pour une lecture rapide.',
    detailedViewDesc: 'Inclut la biographie professionnelle complète et les descriptions de poste.',
    printOptimizedDesc: "Fond blanc propre, optimisé pour l'impression physique.",
    ideThemeDesc: 'Utilise le thème sombre du portfolio. Idéal pour le partage PDF.',
    openInNewTabDesc:
      "S'ouvre dans un nouvel onglet. Utilisez la boîte de dialogue d'impression de votre navigateur (Ctrl+P) pour enregistrer en PDF.",
    cvProfessionalSummary: 'Résumé Professionnel',
    cvTechnicalSkills: 'Compétences Techniques',
    cvProfessionalExperience: 'Expérience Professionnelle',
    cvProjects: 'Projets',
    cvEducation: 'Éducation',
    cvCertifications: 'Certifications',
    cvLanguages: 'Langues',
    phone: 'Téléphone',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    atsFriendlyVersion: 'Version optimisée ATS :',
    atsFriendlyDesc:
      "Cette mise en page est intentionnellement dépourvue d'icônes, de mises en page complexes et de polices personnalisées. Elle utilise du HTML sémantique pur (h1, h2, ul, li) pour assurer une compatibilité maximale avec les systèmes de suivi des candidatures (ATS).",
    loadingAtsCv: 'Chargement du CV ATS...',
    loadingCv: 'Chargement du CV...',
    techLabel: 'Technologies :',
    viewSource: 'Voir le code source',
    viewLive: 'Voir le site en direct',
    errorNoSleep: "Erreur : Les développeurs ne dorment pas. Vous ne pouvez pas fermer l'IDE.",
    exit: 'Quitter',
    exitFullscreen: 'Quitter le plein écran',
    enterFullscreen: 'Plein écran',
    systemShutdown: 'ARRÊT DU SYSTÈME INITIÉ...',
    rebootSystem: 'REDÉMARRER LE SYSTÈME',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, data: dataMap[language], t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
